# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: knowledge/v1/knowledge.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'knowledge/v1/knowledge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cknowledge/v1/knowledge.proto\x12\x0cknowledge.v1\"\x0f\n\rHealthRequest\"\x1c\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"Z\n\x05\x43hunk\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x03 \x01(\x05\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\"5\n\x0eSearchResponse\x12#\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x13.knowledge.v1.Chunk\"?\n\x11IngestTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\"*\n\x12IngestTextResponse\x12\x14\n\x0c\x63hunks_saved\x18\x01 \x01(\x05\x32\xed\x01\n\x10KnowledgeService\x12\x43\n\x06Health\x12\x1b.knowledge.v1.HealthRequest\x1a\x1c.knowledge.v1.HealthResponse\x12\x43\n\x06Search\x12\x1b.knowledge.v1.SearchRequest\x1a\x1c.knowledge.v1.SearchResponse\x12O\n\nIngestText\x12\x1f.knowledge.v1.IngestTextRequest\x1a .knowledge.v1.IngestTextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'knowledge.v1.knowledge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=46
  _globals['_HEALTHREQUEST']._serialized_end=61
  _globals['_HEALTHRESPONSE']._serialized_start=63
  _globals['_HEALTHRESPONSE']._serialized_end=91
  _globals['_SEARCHREQUEST']._serialized_start=93
  _globals['_SEARCHREQUEST']._serialized_end=138
  _globals['_CHUNK']._serialized_start=140
  _globals['_CHUNK']._serialized_end=230
  _globals['_SEARCHRESPONSE']._serialized_start=232
  _globals['_SEARCHRESPONSE']._serialized_end=285
  _globals['_INGESTTEXTREQUEST']._serialized_start=287
  _globals['_INGESTTEXTREQUEST']._serialized_end=350
  _globals['_INGESTTEXTRESPONSE']._serialized_start=352
  _globals['_INGESTTEXTRESPONSE']._serialized_end=394
  _globals['_KNOWLEDGESERVICE']._serialized_start=397
  _globals['_KNOWLEDGESERVICE']._serialized_end=634
# @@protoc_insertion_point(module_scope)
